### ISSUE TITLE
refactor: state handling, initialization, filesystem

### ISSUE THREAD

**Issue by haxibami** [haxibami/hotate#15]
### What

current code for

- state handling
- initialization
- text load & save
- etc.

are: **spaghetti**. 🍝 

### TODO

- [ ] use more home-made hooks for state handling
- [ ] use more `<**Plugin>` for initialization
- [ ] introduce more sophisticated file & text API
